/*
 * /*
copyright  © Sotaya Yakubu
Contact: sotayamy@yahoo.co.uk
*/
/*
This code is free software, distributed under the 
GNU Public license Version 3 http://www.gnu.org/licenses/gpl.html
*/
/*
 *
 * For more information about the application and 
 * the lincensing, check the README file in the main 
 * repo.
 *
 *
 *
 * @author PlaixHax0r
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author PlaixHax0r
 */
public class PlaixCalc extends javax.swing.JFrame {

    /**
     * Creates new form PlaixCalc
     */
    public PlaixCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        One1 = new javax.swing.JButton();
        TextField = new javax.swing.JTextField();
        Seven = new javax.swing.JButton();
        Eight = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        Addition = new javax.swing.JButton();
        Subtraction = new javax.swing.JButton();
        Multiplication = new javax.swing.JButton();
        Division = new javax.swing.JButton();
        Equals = new javax.swing.JButton();
        C = new javax.swing.JButton();
        Period = new javax.swing.JButton();
        BackSpace = new javax.swing.JButton();
        One = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        Plus_Minus = new javax.swing.JButton();

        One1.setText("1");
        One1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                One1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        TextField.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        TextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Seven.setText("7");
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });

        Eight.setText("8");
        Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightActionPerformed(evt);
            }
        });

        Nine.setText("9");
        Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineActionPerformed(evt);
            }
        });

        Zero.setText("0");
        Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroActionPerformed(evt);
            }
        });

        Addition.setText("+");
        Addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionActionPerformed(evt);
            }
        });

        Subtraction.setText("-");
        Subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractionActionPerformed(evt);
            }
        });

        Multiplication.setText("x");
        Multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicationActionPerformed(evt);
            }
        });

        Division.setText("/");
        Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionActionPerformed(evt);
            }
        });

        Equals.setText("=");
        Equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualsActionPerformed(evt);
            }
        });

        C.setBackground(new java.awt.Color(255, 255, 255));
        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        Period.setText(".");
        Period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeriodActionPerformed(evt);
            }
        });

        BackSpace.setText("CE");
        BackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackSpaceActionPerformed(evt);
            }
        });

        One.setText("1");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });

        Two.setText("2");
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });

        Three.setText("3");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });

        Six.setText("6");
        Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixActionPerformed(evt);
            }
        });

        Five.setText("5");
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });

        Four.setText("4");
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });

        Plus_Minus.setText("+/-");
        Plus_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plus_MinusActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(TextField))
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(Seven, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(Eight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(10, 10, 10)
                                        .add(Nine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(Four, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(Five, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(Six, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(layout.createSequentialGroup()
                                                .add(One, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(18, 18, 18)
                                                .add(Two, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(layout.createSequentialGroup()
                                                .add(Zero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(Plus_Minus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(Period, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(Three, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(Addition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(8, 8, 8)
                                        .add(Subtraction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(Division, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(Multiplication, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                            .add(layout.createSequentialGroup()
                                .add(C, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(BackSpace, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(Equals, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(C, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BackSpace, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Equals, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Seven, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Eight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Nine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Addition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Four, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Five, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Six, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Subtraction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(One, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Two, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Three, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Multiplication, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(Zero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(Plus_Minus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(Period, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(Division, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>
    
    boolean equalPress=false;
    boolean signChange=false;
    private void NineActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("9");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"9");
          //  signChange=false;
        }
    }                                    

    private void OneActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("1");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"1");
           // signChange=false;
        }
    }                                   

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("2");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"2");
           // signChange=false;
        }
    }                                   

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("3");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"3");
            //signChange=false;
        }
    }                                     

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("4");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"4");
            signChange=false;
        }
    }                                    

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("5");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"5");
           // signChange=false;
        }
    }                                    

    private void SixActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("6");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"6");
           // signChange=false;
        }
    }                                   

    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("7");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"7");
            //signChange=false;
        }
    }                                     

    private void EightActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("8");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"8");
            //signChange=false;
        }
    }                                     

    private void ZeroActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(equalPress==true && signChange==false) {
            TextField.setText("0");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+"0");
            //signChange=false;
        }
    }                                    

    private void EqualsActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        signChange=false;
        try{
            String text = TextField.getText();
            String firstNum, secondNum;
            long num1, num2;
            float num3, num4;
            if(text.contains("+")){
                firstNum = text.substring(0, text.indexOf("+"));
                secondNum = text.substring(text.indexOf("+")+1, text.length());

                num1 = (long)(Double.parseDouble(firstNum));
                num2 = (long)(Double.parseDouble(secondNum));

                TextField.setText(Long.toString(num1+num2));
            }else if(text.contains("-") && !text.contains("/") && !text.contains("x")){
                firstNum = text.substring(0,text.lastIndexOf("-"));
                secondNum = text.substring(text.lastIndexOf("-")+1, text.length());
                num1 = (long)(Double.parseDouble(firstNum));
                num2 = (long)(Double.parseDouble(secondNum));
                TextField.setText(Long.toString(num1-num2));
            }else if(text.contains("x")){
                firstNum = text.substring(0,text.indexOf("x"));
                secondNum = text.substring(text.indexOf("x")+1, text.length());
                num1 = (long)(Double.parseDouble(firstNum));
                num2 = (long)(Double.parseDouble(secondNum));
                TextField.setText(Long.toString(num1*num2));    
            }else if(text.contains("/")){
                firstNum = text.substring(0,text.indexOf("/"));
                secondNum = text.substring(text.indexOf("/")+1, text.length());
                num3 = (float)(Double.parseDouble(firstNum));
                num4 = (float)(Double.parseDouble(secondNum));
                float result = num3/num4;
                int resultInt = (int)result;
                if(result/resultInt == 1){
                    TextField.setText(Integer.toString(resultInt));
                } else if(num3 == 0){
                    TextField.setText("0");    
                }else{
                    TextField.setText(Float.toString(result));    
                }
            }else{}
            equalPress=true;
        
        }catch(ArithmeticException x){
            TextField.setText("Undefined");
        }catch(NumberFormatException x){
            TextField.setText("Incompatable");
            equalPress=true;
        }
    }                                      

    private void AdditionActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
      
        TextField.setText(TextField.getText()+"+");
        signChange=true;
    }                                        

    private void SubtractionActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        TextField.setText(TextField.getText()+"-");
        signChange=true;
    }                                           

    private void MultiplicationActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        TextField.setText(TextField.getText()+"x");
        signChange=true;
    }                                              

    private void DivisionActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        TextField.setText(TextField.getText()+"/");
        signChange=true;
    }                                        

    private void One1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void CActionPerformed(java.awt.event.ActionEvent evt) {                                  
        // TODO add your handling code here:
        TextField.setText("");
    }                                 

    private void PeriodActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if(equalPress==true) {
            TextField.setText(".");
            equalPress=false;
        }
        else {
            TextField.setText(TextField.getText()+".");
        }
    }                                      

    private void BackSpaceActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        TextField.setText (TextField.getText ().substring (0, TextField.getText ().length () - 1));
    }                                         

    private void Plus_MinusActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        TextField.setText("-"+TextField.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaixCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaixCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaixCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaixCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaixCalc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton Addition;
    private javax.swing.JButton BackSpace;
    private javax.swing.JButton C;
    private javax.swing.JButton Division;
    private javax.swing.JButton Eight;
    private javax.swing.JButton Equals;
    private javax.swing.JButton Five;
    private javax.swing.JButton Four;
    private javax.swing.JButton Multiplication;
    private javax.swing.JButton Nine;
    private javax.swing.JButton One;
    private javax.swing.JButton One1;
    private javax.swing.JButton Period;
    private javax.swing.JButton Plus_Minus;
    private javax.swing.JButton Seven;
    private javax.swing.JButton Six;
    private javax.swing.JButton Subtraction;
    private javax.swing.JTextField TextField;
    private javax.swing.JButton Three;
    private javax.swing.JButton Two;
    private javax.swing.JButton Zero;
    // End of variables declaration
}
